server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/user
    username: hosamyoussef
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet